name: example

channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  # dependencies
  - python=3.10
  - numpy>=1.25.2
  - matplotlib>=3.7.2
  # build dependencies
  - pip
  - pip:
    # dependencies
    - mlflow>=2.6.0
    - typer[all]>=0.9.0
    # ## notebook
    - notebook>=7.0.3
    - voila>=0.5.1
    - ipywidgets>=8.1.0
